# Generated by Django 6.0.3 on 2026-04-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='employee',
        ),
        migrations.DeleteModel(
            name='BankingDetail',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
